### PR TITLE
feat: add default logout implementation

### PR DESCRIPTION
**Pull request by mattnichols**
# Summary of Changes

This adds a default implementation for logout. This will fix errors resulting in calling logout when the accessor does not have an implementation.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by kcpotluri — APPROVED** [review]
LGTM. This can remove most of the MR's in the service we are writing.

**Comment by mattnichols** [comment]
> LGTM. This can remove most of the MR's in the service we are writing.

? How's that? 🤔

**Comment by kcpotluri** [comment]
If there is default already implemented(which is the case here), we don't have to write in individual service right. Unless we need to implement some thing custom which we don't do in most of the cases.

**Comment by kcpotluri** [comment]
Oh is this not done at the controller level 🤔

**Review by RyanJones08 — APPROVED** [review]
Approved

**Comment by mattnichols** [comment]
> If there is default already implemented(which is the case here), we don't have to write in individual service right. Unless we need to implement some thing custom which we don't do in most of the cases.

This just provides a default for the logout accessor method that doesn't raise an error. Probably less than half of the accessors have a logout implemented because there is nothing they can do. If you can terminate upstream sessions or have any other cleanup that can be done when the session is over, you should implement your own logout method on the id accessor! It is more tidy and much more secure!

**Pull request merged**
